### PR TITLE
Updating Android App dependencies to latest for AS Electric Eel

### PR DESCRIPTION
**Pull request by childofthehorn**
Dependency Update to Java 11, Android 33, and all other required updates for AS Electric Eel

### CODE REVIEW

**Comment by Filmaluco** [comment]
Hi @childofthehorn :D Thanks for the PR, can you also update the gradle wrapper file? 
I am not mistaken you just need to run` gradle wrapper` to generate the file

**Comment by childofthehorn** [comment]
@Filmaluco You should find that done and a few other upgrades. I will also be submitting another PR that migrates everything to Gradle 8.0 in a separate PR as it involves more choices. You will find that I have set this build up now to also not have any compiler warnings for crossed versions of Java, so migration should be pretty quick.

**Comment by childofthehorn** [comment]
@Filmaluco Is there anything else you are looking for here?

**Comment by Filmaluco** [comment]
> @Filmaluco Is there anything else you are looking for here? 

Sorry came back yesterday from vacations haven't taken a good look at it. Will take a deep look tomorrow :D

**Comment by sdsantos** [comment]
Thanks @childofthehorn!

**Pull request merged**
